name: app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  barcode_scan2: ^4.3.3
  flutter:
    sdk: flutter
  gsheets: ^0.4.2
  http: 0.13.6
  mobile_scanner: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/credentials.json

